### ISSUE TITLE
Authenticateion document secret data field use data instead of stringData. 

### ISSUE THREAD

**Issue by c6h3un** [tektoncd/website#176]
secret spec data field name is not stringData is data instead. This will cause the username, password, and ssh-privatekey will not be base64 decoded in the pod. which caused git resource error in the first step. 
# Expected Behavior
```
apiVersion: v1
kind: Secret
metadata:
  annotations:
    tekton.dev/git-0: https://github.com
    tekton.dev/git-1: https://gitlab.com
    tekton.dev/docker-0: https://gcr.io
type: kubernetes.io/basic-auth
data:
  username: <cleartext username>
  password: <cleartext password>
```
```
apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
  annotations:
    tekton.dev/git-0: github.com # Described below
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: <private-key>
  # This is non-standard, but its use is encouraged to make this more secure.
  # If it is not provided then the git server's public key will be requested
  # when the repo is first fetched.
  known_hosts: <known-hosts>
```
# Actual Behavior
```
apiVersion: v1
kind: Secret
metadata:
  annotations:
    tekton.dev/git-0: https://github.com
    tekton.dev/git-1: https://gitlab.com
    tekton.dev/docker-0: https://gcr.io
type: kubernetes.io/basic-auth
stringData:
  username: <cleartext username>
  password: <cleartext password>
```
```
apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
  annotations:
    tekton.dev/git-0: github.com # Described below
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: <private-key>
  # This is non-standard, but its use is encouraged to make this more secure.
  # If it is not provided then the git server's public key will be requested
 # when the repo is first fetched.
  known_hosts: <known-hosts>
```
# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info
