### ISSUE TITLE
sync.py does not include subdirectories.

### ISSUE THREAD

**Issue by wlynch** [tektoncd/website#250]
# Expected Behavior

I can configure sync.py to include files from subdirectories.

# Actual Behavior

The following attempts at configuration fail:

```yaml
  folders:
    docs:
      index: README.md
      include: ['**/*.md']
```
[no files included](https://app.netlify.com/sites/tekton/deploys/6035624d588f1200078285dc)

---

```yaml
  folders:
    docs:
      index: README.md
      include: ['*.md']
    docs/api:
      index: README.md
      include: ['*.md']
```
[build fails](https://app.netlify.com/sites/tekton/deploys/603560d771b9000007b338e5)

---

```yaml
  folders:
    docs:
      index: README.md
      include: ['**.md']
```
[no subdirectories included](https://app.netlify.com/sites/tekton/deploys/603563f0a527940008696d6d)

---

```yaml
  folders:
    docs:
      index: README.md
      include: ['*.md', '**/*.md']
```

[no subdirectories included](https://app.netlify.com/sites/tekton/deploys/60356510c62a3f00087607a3)

**Comment by wlynch** [comment]
pebkac :)

the correct format should be:

```yaml
  folders:
    docs:
      index: README.md
      include: ['*.md']
    docs/api:
      target: api
      index: README.md
      include: ['*.md']
```

I'll make a PR to call this out explicitly in the docs.
