### ISSUE TITLE
EventListeners docs say to use extenisons. in EventListner.triggers.interceptors.cel.overlays.key value but that doesnt work

### ISSUE THREAD

**Issue by itewk** [tektoncd/website#282]
# Expected Behavior

The docs show that to set a value for an extension to do:

EventListener
```
  triggers:
    - name: cel-trig
      interceptors:
        - cel:
            overlays:
            - key: extensions.truncated_sha
              expression: "body.pull_request.head.sha.truncate(7)"
            - key: extensions.branch_name
              expression: "body.ref.split('/')[2]"
```

TriggerBinding
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: ClusterTriggerBinding
metadata:
  name: test
spec:
  params:
  - name: truncated-sha
    value: $(extensions.truncated_sha)
  - name: branch-name
    value: $(extensions.branch_name)
```

# Actual Behavior

But from experimentation with Red Hat OpenShift Pipelines 1.4.1 that doesnt work and gives error. What works is:

EventListener
```
  triggers:
    - name: cel-trig
      interceptors:
        - cel:
            overlays:
            - key: truncated_sha
              expression: "body.pull_request.head.sha.truncate(7)"
            - key: branch_name
              expression: "body.ref.split('/')[2]"
```

TriggerBinding

```
apiVersion: triggers.tekton.dev/v1alpha1
kind: ClusterTriggerBinding
metadata:
  name: test
spec:
  params:
  - name: truncated-sha
    value: $(extensions.truncated_sha)
  - name: branch-name
    value: $(extensions.branch_name)
 ````

The difference being dropping the `extensions.` in the EventListener in the overlay key value.

# Steps to Reproduce the Problem

1. create an EventListener with an interceptor and try to use that value in a TriggerBinding

# Additional Info
The weird thing is before I upgraded to Pipelines v0.22.0 and Triggers v0.12.1 this worked as documented, I had to have the `extensions.` in there (dont know what version i was on before). But then after upgrading, eventlistener broke and through experimentation I figured this out.

I don't know if this is expected behavior and thus a doc bug, or unexpected behavior and the docs are correct.

**Comment by afrittoli** [comment]
Hello @itewk - thank you for your report.

I see that using `extensions` is documented in triggers v0.12.1 docs https://tekton.dev/vault/triggers-v0.12.1/eventlisteners/#overlays .
In the latest docs - using overlays is documented mostly in https://tekton.dev/docs/triggers/cel_expressions/ - where the docs seems to be correct.

Could you point me to the right place in the docs that seems to be incorrect?

**Comment by itewk** [comment]
@afrittoli https://tekton.dev/vault/triggers-v0.12.1/eventlisteners/#overlays shows doing:

```
  triggers:
    - name: cel-trig
      interceptors:
        - cel:
            overlays:
            - key: extensions.truncated_sha
              expression: "body.pull_request.head.sha.truncate(7)"
            - key: extensions.branch_name
              expression: "body.ref.split('/')[2]"
```

but from my experimintation i had to do:

```
  triggers:
    - name: cel-trig
      interceptors:
        - cel:
            overlays:
            - key: truncated_sha
              expression: "body.pull_request.head.sha.truncate(7)"
            - key: branch_name
              expression: "body.ref.split('/')[2]"
```

So which is correct, the doc, or what I found to be true in experimentation? basically it is a bug doc or an implementation bug or am I crazy?
