### ISSUE TITLE
Configuring Interceptors

### ISSUE THREAD

**Issue by InfoSec812** [tektoncd/website#335]
# Expected Behavior

That I could copy and modify the example interceptor and use it in OpenShift 4.9

# Actual Behavior

I get a validation error on the following resource:

```yaml
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: clms-frontend-pipeline-webhook-listener
  namespace: clms-devops
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - name: cel-trig
      interceptors:
        - ref:
            name: cel
          params:
          - name: "overlays"
            value:
            - key: branch_name
              expression: "body.ref.split('/')[2]"
    - bindings:
        - kind: TriggerBinding
          ref: gitea-trigger-bindings
      name: gitea-webhook-trigger
      template:
        ref: example
```

The error looks like:

![image](https://user-images.githubusercontent.com/99691/149945686-54823ffd-2967-44c0-a03e-1254dabf1ada.png)

`admission webhook "validation.webhook.triggers.tekton.dev" denied the request: validation failed: expected exactly one, got neither: spec.triggers[0].template, spec.triggers[0].triggerRef`

# Steps to Reproduce the Problem

1. Attempt to create the EventListener described above

# Additional Info
