### ISSUE TITLE
Pipelines

### ISSUE THREAD

**Issue by oDevArc** [tektoncd/website#533]
Hello

In this section https://tekton.dev/docs/pipelines/pipelines/#guard-task-execution-using-when-expressions it seems that the example given for a task named `name: first-create-file` cannot work because the `when` clause of the next task `echo-file-exists` is calling the result of the task by this expression : `input: "$(tasks.check-file.results.exists)"` which fot me is trying to get the result of task named `check-file` which is not existing ! the good name would be `first-create-file` and the the when section would be: 

```yaml
tasks:
  - name: first-create-file
    when:
      - input: "$(params.path)"
        operator: in
        values: ["README.md"]
    taskRef:
      name: first-create-file
---
tasks:
  - name: echo-file-exists
    when:
      - input: "$(tasks.first-create-file.results.exists)" #<<<< this line
```

I'm not sure of me :-) because I'm learning !
