### ISSUE TITLE
Tasks - "yaml" syntax highlighting 

### ISSUE THREAD

**Issue by michaelsatish** [tektoncd/website#540]
Hello,

The "yaml" syntax highlighting is missing in the below sections.  

1. https://tekton.dev/docs/pipelines/tasks/#task-vs-clustertask
2. https://tekton.dev/docs/pipelines/tasks/#defining-steps

**Current syntax highlighting :**

```
yaml apiVersion: tekton.dev/v1 kind: Pipeline metadata: name: demo-pipeline spec: tasks: - name: build-skaffold-web taskRef: 
resolver: cluster params: - name: kind value: task - name: name value: build-push - name: namespace value: default 
```

**How it should highlight:**

```yaml 
apiVersion: tekton.dev/v1 
kind: Pipeline 
metadata: name: demo-pipeline 
spec: 
  tasks: 
    - name: build-skaffold-web 
       taskRef: 
         resolver: cluster 
       params: 
          - name: kind 
            value: task 
          - name: name 
            value: build-push 
          - name: namespace 
            value: default 
```
