### ISSUE TITLE
Configuring bitbucket interceptor EventTypes documentation issue

### ISSUE THREAD

**Issue by dcheng1248** [tektoncd/website#631]
Hi, I was referring to [this](https://tekton.dev/docs/triggers/interceptors/#bitbucket-interceptors) documentation for bitbucket interceptor configuration. We use bitbucket cloud. 
I first configured the eventTypes accordingly:
```
  params:
    - name: eventTypes
      value:
        - repo:push
```
However, a webhook request did not trigger the pipeline. I looked into the [source code](https://github.com/tektoncd/triggers/blob/main/pkg/interceptors/bitbucket/bitbucket.go) and saw the eventTypes is defined as an array of strings, so I tried this:
```
  params:
    - name: eventTypes
      value:
        - [repo:push]
```
And it works. So it seems that the brackets are necessary, but not documented accordingly.
