### ISSUE TITLE
"Edit this page" leads to 404 for sub pages

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/website#65]
# Expected Behavior
Clicking the 'Edit this page' link should bring me to the corresponding file in GitHub.

# Actual Behavior
Sub-pages under 'Tasks and Pipelines' and 'Triggers' lead to a 404

# Steps to Reproduce the Problem

1. Go to https://tekton.netlify.com/docs/pipelines/pipelineruns/
2. Click 'Edit this page' in the top right corner
3. Land on https://github.com/tektoncd/website//edit/master/content/en/docs/Pipelines/pipelineruns.md which gives a 404

# Additional Info
Sub-pages for Pipelines and Triggers are being synced from the docs folder in their respective repos, so the 'Edit this page' links pointing to the website repo are wrong.

**Comment by AlanGreene** [comment]
PRs open against dashboard + each of the repos currently syncing docs to the website. Ideally in future we wouldn't need to make this kind of change in each repo, but the alternative would require changes to the script to detect and modify the frontmatter block inside a HTML comment in a markdown file... This seems like it would be more likely to cause problems so I went with the simpler approach for now.

**Comment by AlanGreene** [comment]
Looks like this is back... https://github.com/tektoncd/website/issues/186#issuecomment-717734692

/reopen

**Comment by popcor255** [comment]
#187 There is a fix @AlanGreene

**Comment by AlanGreene** [comment]
@popcor255 #187 does fix a number of cases of broken links, but as far as I can tell the 'Edit this page' links are a totally different issue. I fixed this originally back in May by adding some config to the frontmatter of the root docs page for each project (see the PRs above) that should be read to determine the project base URL when constructing that link specifically. I'll see if I can figure out why it's broken again...

**Comment by AlanGreene** [comment]
This is still an issue, the edit links are broken and we should fix them.
/reopen

**Comment by afrittoli** [comment]
Looking at the [latest docsy docs](https://www.docsy.dev/docs/adding-content/repository-links/#path_base_for_github_subdir-optional) I think this could be solved by:
- updating docsy - see https://github.com/tektoncd/website/pull/303
- updating the content matter in the various projects to include the following type of data

```
---
title: Some super section
path_base_for_github_subdir:
  from: content/some-section/(.*?)/_index.md
  to: $1/README.md
cascade:
  github_repo: https://github.com/some-username/another-repo/
  github_subdir: docs
  path_base_for_github_subdir: content/some-section
...
---
```
